apiVersion: v1
kind: ServiceAccount
metadata:
  name: nl-fork-provisioner
  namespace: nl-fleet-production
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nl-fork-provisioner
  namespace: nl-fork
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nl-fork-provisioner
  namespace: nl-fork
subjects:
  - kind: ServiceAccount
    name: nl-fork-provisioner
    namespace: nl-fleet-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nl-fork-provisioner
---
apiVersion: v1
kind: Namespace
metadata:
  name: nl-fork
