# Deploy NL public demo WITHOUT Docker (Windows / local dev).
# Starts SessionHost.Web in demo mode + Python loop bridge.
#
# Usage:
#   powershell -File scripts/deploy-demo-native.ps1
#   powershell -File scripts/stop-demo-native.ps1
param(
    [switch]$SkipBuild,
    [int]$BridgeInterval = 6
)

$ErrorActionPreference = "Stop"
$repo = Split-Path $PSScriptRoot -Parent
$stateDir = Join-Path $repo "artifacts\demo-native"
$stateFile = Join-Path $stateDir "state.json"
$envFile = Join-Path $repo "docker\.env"
$dataRoot = Join-Path $stateDir "data"
$logDir = Join-Path $stateDir "logs"
$busToken = "nl-bus-" + ([guid]::NewGuid().ToString("N"))
$operatorKey = "nl-op-" + ([guid]::NewGuid().ToString("N"))
$baseUrl = "http://127.0.0.1:27020"
$wsUrl = "ws://127.0.0.1:27021/nl/v1?token=$busToken"
$healthUrl = "$baseUrl/health"
$demoUrl = "$baseUrl/api/v1/demo/status"

function Write-DemoEnvFile {
    @"
# Auto-generated by deploy-demo-native.ps1 - also used if you later deploy with Docker on a VPS.
NL_DEMO_DOMAIN=localhost
NL_BUS_TOKEN=$busToken
NL_OPERATOR_KEY=$operatorKey
NL_PUBLIC_HTTP=http://localhost
NL_PUBLIC_WS=ws://localhost/nl/v1
NL_PUBLIC_MOD_HTTP=http://localhost
NL_CORS_ORIGINS=http://localhost
"@ | Set-Content -Path $envFile -Encoding UTF8
}

function Ensure-PythonBridgeDeps {
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "SilentlyContinue"
    python -c "import websocket" 2>$null | Out-Null
    $missing = $LASTEXITCODE -ne 0
    $ErrorActionPreference = $prev
    if ($missing) {
        Write-Host "Installing Python websocket-client..."
        python -m pip install --quiet websocket-client
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to install websocket-client. Run: python -m pip install websocket-client"
        }
    }
}

function Stop-ExistingDemo {
    if (Test-Path $stateFile) {
        $prev = Get-Content $stateFile -Raw | ConvertFrom-Json
        foreach ($procId in @($prev.serverPid, $prev.bridgePid)) {
            if ($procId) {
                Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue
            }
        }
    }
    Get-Process -Name "dotnet" -ErrorAction SilentlyContinue | Where-Object {
        $_.Path -and $_.CommandLine -match "NL.SessionHost.Web"
    } | Stop-Process -Force -ErrorAction SilentlyContinue
}

New-Item -ItemType Directory -Force -Path $stateDir, $dataRoot, $logDir | Out-Null
Stop-ExistingDemo
Write-DemoEnvFile
Ensure-PythonBridgeDeps

if (-not $SkipBuild) {
    Write-Host "Building SessionHost.Web..."
    dotnet build (Join-Path $repo "src\NL.SessionHost.Web\NL.SessionHost.Web.csproj") -c Release | Out-Null
}

$serverLog = Join-Path $logDir "session-server.log"
$serverErrLog = Join-Path $logDir "session-server.err.log"
$bridgeLog = Join-Path $logDir "demo-bridge.log"
$bridgeErrLog = Join-Path $logDir "demo-bridge.err.log"

$serverEnv = @{
    NL_BIND = "127.0.0.1"
    NL_HTTP_PORT = "27020"
    NL_WS_PORT = "27021"
    NL_DATA_ROOT = $dataRoot
    NL_PUBLIC_MODE = "true"
    NL_DEMO_MODE = "true"
    NL_DEMO_CONFIG = "demo.nle"
    NL_DEMO_RESET_INTERVAL_MINUTES = "0"
    NL_DEMO_STARTUP_DELAY_MS = "500"
    NL_BUS_TOKEN = $busToken
    NL_OPERATOR_KEY = $operatorKey
    NL_PUBLIC_HTTP = $baseUrl
    NL_PUBLIC_WS = "ws://127.0.0.1:27021/nl/v1"
    NL_PUBLIC_MOD_HTTP = $baseUrl
    NL_CORS_ORIGINS = $baseUrl
    NL_HARDENING = "true"
}

Write-Host "=== NL demo deploy (native Windows) ===" -ForegroundColor Cyan
Write-Host "Data:      $dataRoot"
Write-Host "Dashboard: $baseUrl/"
Write-Host "Operator:  $baseUrl/operator.html"
Write-Host "Spectator: $baseUrl/"
Write-Host ""

$serverStartInfo = @{
    FilePath = "dotnet"
    ArgumentList = @(
        "run", "--project", (Join-Path $repo "src\NL.SessionHost.Web\NL.SessionHost.Web.csproj"),
        "-c", "Release", "--no-build"
    )
    WorkingDirectory = $repo
    RedirectStandardOutput = $serverLog
    RedirectStandardError = $serverErrLog
    PassThru = $true
    WindowStyle = "Hidden"
}
foreach ($kv in $serverEnv.GetEnumerator()) {
    Set-Item -Path "Env:$($kv.Key)" -Value $kv.Value
}

$serverProc = Start-Process @serverStartInfo
Start-Sleep -Seconds 3

Write-Host "Waiting for session server health..."
$healthy = $false
for ($i = 0; $i -lt 45; $i++) {
    try {
        $h = Invoke-RestMethod -Uri $healthUrl -ErrorAction Stop
        if ($h.status -eq "ok") {
            $healthy = $true
            break
        }
    } catch { }
    Start-Sleep -Seconds 2
}
if (-not $healthy) {
    Write-Error "Session server failed health check. See $serverLog and $serverErrLog"
}

# Give demo hosted service time to apply profile and start NL.Server session
Start-Sleep -Seconds 4

$bridgeScript = Join-Path $repo "integrations\python\nl_bridge.py"
$bridgeProc = Start-Process -FilePath "python" -ArgumentList @(
    $bridgeScript,
    "--url", $wsUrl,
    "--loop",
    "--interval", "$BridgeInterval"
) -WorkingDirectory $repo -RedirectStandardOutput $bridgeLog -RedirectStandardError $bridgeErrLog -PassThru -WindowStyle Hidden

Write-Host "Waiting for demo loop (decisions > 0)..."
$demoOk = $false
for ($i = 0; $i -lt 40; $i++) {
    try {
        $demo = Invoke-RestMethod -Uri $demoUrl -ErrorAction Stop
        if ($demo.sessionRunning -and $demo.decisions -gt 0) {
            $demoOk = $true
            break
        }
    } catch { }
    Start-Sleep -Seconds 2
}

@{
    serverPid = $serverProc.Id
    bridgePid = $bridgeProc.Id
    busToken = $busToken
    operatorKey = $operatorKey
    baseUrl = $baseUrl
    wsUrl = $wsUrl
    deployedAt = (Get-Date).ToString("o")
} | ConvertTo-Json | Set-Content -Path $stateFile -Encoding UTF8

Write-Host ""
Write-Host "Demo is UP" -ForegroundColor Green
Write-Host "  Watch:     $baseUrl/"
Write-Host "  Operator:  $baseUrl/operator.html"
Write-Host "  Editor:    $baseUrl/editor.html"
Write-Host "  Moderation:$baseUrl/moderation.html"
Write-Host "  Demo API:  $demoUrl"
Write-Host ""
Write-Host "Operator key (paste in operator page):" -ForegroundColor Yellow
Write-Host "  $operatorKey"
Write-Host ""
Write-Host "Stop: powershell -File scripts/stop-demo-native.ps1"
Write-Host "Logs: $logDir"

if (-not $demoOk) {
    Write-Host "Warning: demo session running but decisions still 0 - check $bridgeLog" -ForegroundColor Yellow
} else {
    $demo = Invoke-RestMethod -Uri $demoUrl
    Write-Host "Demo loop: sessionRunning=$($demo.sessionRunning) decisions=$($demo.decisions)" -ForegroundColor Green
}
