# Phase 11 — start distribution stack (client packages + onboarding on cutover config)
param(
    [switch]$SkipBuild,
    [switch]$SkipForkImages,
    [switch]$SkipClientPackage,
    [switch]$Validate
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-PortInUse([int]$Port) {
    try {
        return (Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue).TcpTestSucceeded
    } catch {
        return $false
    }
}

function New-RandomHex([int]$Bytes = 32) {
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLowerInvariant()
}

function Write-DistributionEnvFile {
    param([string]$HostDataRoot)
    $envPath = Join-Path $Root "docker\distribution-fleet.env"
    $hostPath = $HostDataRoot.Replace('\', '/')
    $operatorKey = New-RandomHex 16
    $busToken = New-RandomHex 16
    $steamKey = New-RandomHex 16
    @(
        "# Auto-generated by nl-distribution-stack-up.ps1"
        "NL_FORK_DOCKER_WORKSPACE_HOST_ROOT=$hostPath"
        "NL_OPERATOR_KEY=$operatorKey"
        "NL_BUS_TOKEN=$busToken"
        "STEAM_WEB_API_KEY=$steamKey"
    ) | Set-Content -Path $envPath -Encoding ASCII
    Write-Host ("Operator key (save for distribution-ops): {0}" -f $operatorKey) -ForegroundColor Yellow
    $script:GeneratedOperatorKey = $operatorKey
}

Write-Host "=== NL Phase 11 distribution stack ===" -ForegroundColor Cyan

foreach ($port in @(27020, 443, 8443)) {
    if (Test-PortInUse $port) {
        throw ("Port {0} busy - stop other NL stacks first." -f $port)
    }
}

if (-not $SkipClientPackage) {
    & (Join-Path $Root "scripts/build-nl-client-package.ps1") -Version "1.0.0"
    if ($LASTEXITCODE -ne 0) { throw "build-nl-client-package failed" }
}

$hostData = Join-Path $Root "docker\distribution-data"
New-Item -ItemType Directory -Force -Path $hostData | Out-Null
Write-DistributionEnvFile $hostData

if (-not $SkipForkImages) {
    & (Join-Path $Root "scripts/build-fork-images.ps1") -Images @("hello-fork", "minecraft", "beamng")
    if ($LASTEXITCODE -ne 0) { throw "build-fork-images failed" }
}

$composeArgs = @("compose", "-f", "docker/docker-compose.distribution.yml", "up")
if (-not $SkipBuild) { $composeArgs += "--build" }
$composeArgs += @("-d")
& docker @composeArgs
if ($LASTEXITCODE -ne 0) { throw "docker compose up failed" }

function Wait-HttpOk([string]$Url, [int]$TimeoutSec = 240) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri $Url -TimeoutSec 5 | Out-Null
            return $true
        } catch {
            Start-Sleep -Seconds 3
        }
    }
    return $false
}

if (-not (Wait-HttpOk "http://127.0.0.1:27020/health")) {
    throw "session-host /health failed"
}

Write-Host "Landing:       http://127.0.0.1:27020/play.html" -ForegroundColor Green
Write-Host "Download:      http://127.0.0.1:27020/download.html" -ForegroundColor Green
Write-Host "Distribution:  http://127.0.0.1:27020/distribution-ops.html" -ForegroundColor Green

if ($Validate) {
    Write-Host ""
    & (Join-Path $Root "scripts/nl-distribution-validate.ps1") -OperatorKey $script:GeneratedOperatorKey
}
