# Phase 6 — start general availability stack (production fleet + catalog + SLA)
param(
    [switch]$SkipBuild,
    [switch]$SkipForkImage,
    [switch]$Validate
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-PortInUse([int]$Port) {
    try {
        return (Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue).TcpTestSucceeded
    } catch {
        return $false
    }
}

function New-RandomHex([int]$Bytes = 32) {
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLowerInvariant()
}

function Write-GaEnvFile {
    param([string]$HostDataRoot)
    $envPath = Join-Path $Root "docker\ga-fleet.env"
    $hostPath = $HostDataRoot.Replace('\', '/')
    $operatorKey = New-RandomHex 16
    $busToken = New-RandomHex 16
    @(
        "# Auto-generated by nl-ga-stack-up.ps1"
        "NL_FORK_DOCKER_WORKSPACE_HOST_ROOT=$hostPath"
        "NL_OPERATOR_KEY=$operatorKey"
        "NL_BUS_TOKEN=$busToken"
    ) | Set-Content -Path $envPath -Encoding ASCII
    Write-Host ("Wrote {0}" -f $envPath) -ForegroundColor DarkGray
    Write-Host ("Operator key (save for ga-ops): {0}" -f $operatorKey) -ForegroundColor Yellow
    $script:GeneratedOperatorKey = $operatorKey
}

Write-Host "=== NL Phase 6 general availability stack ===" -ForegroundColor Cyan

foreach ($port in @(27020, 443, 8443)) {
    if (Test-PortInUse $port) {
        Write-Host ("Port {0} busy - stop other NL stacks first." -f $port) -ForegroundColor Yellow
        throw ("Port {0} busy." -f $port)
    }
}

$hostData = Join-Path $Root "docker\ga-data"
New-Item -ItemType Directory -Force -Path $hostData | Out-Null
Write-GaEnvFile $hostData

if (-not $SkipForkImage) {
    Write-Host "Building nl-fork-hello:latest ..." -ForegroundColor Yellow
    docker build -f docker/fork-hello/Dockerfile -t nl-fork-hello:latest .
    if ($LASTEXITCODE -ne 0) { throw "docker build failed" }
}

$composeArgs = @("compose", "-f", "docker/docker-compose.ga-fleet.yml", "up")
if (-not $SkipBuild) { $composeArgs += "--build" }
$composeArgs += @("-d")
& docker @composeArgs
if ($LASTEXITCODE -ne 0) { throw "docker compose up failed" }

function Wait-HttpOk([string]$Url, [int]$TimeoutSec = 240) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri $Url -TimeoutSec 5 | Out-Null
            return $true
        } catch {
            Start-Sleep -Seconds 3
        }
    }
    return $false
}

if (-not (Wait-HttpOk "http://127.0.0.1:27020/health")) {
    & docker compose -f docker/docker-compose.ga-fleet.yml logs session-host --tail 40
    throw "session-host /health failed"
}

Write-Host "GA signup:     http://127.0.0.1:27020/ga.html" -ForegroundColor Green
Write-Host "GA ops:        http://127.0.0.1:27020/ga-ops.html" -ForegroundColor Green
Write-Host "Game catalog:  http://127.0.0.1:27020/fork-catalog.html" -ForegroundColor Green
Write-Host "NL Client:     http://127.0.0.1:27020/nl-client.html" -ForegroundColor Green

if ($Validate) {
    Write-Host ""
    & (Join-Path $Root "scripts/nl-ga-validate.ps1") -OperatorKey $script:GeneratedOperatorKey
}
