# Phase 10 — start production cutover stack (production flags, no dev shortcuts)
param(
    [switch]$SkipBuild,
    [switch]$SkipForkImages,
    [switch]$Validate
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-PortInUse([int]$Port) {
    try {
        return (Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue).TcpTestSucceeded
    } catch {
        return $false
    }
}

function New-RandomHex([int]$Bytes = 32) {
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLowerInvariant()
}

function Write-CutoverEnvFile {
    param([string]$HostDataRoot)
    $envPath = Join-Path $Root "docker\production-cutover-fleet.env"
    $hostPath = $HostDataRoot.Replace('\', '/')
    $operatorKey = New-RandomHex 16
    $busToken = New-RandomHex 16
    $steamKey = New-RandomHex 16
    @(
        "# Auto-generated by nl-production-cutover-stack-up.ps1"
        "NL_FORK_DOCKER_WORKSPACE_HOST_ROOT=$hostPath"
        "NL_OPERATOR_KEY=$operatorKey"
        "NL_BUS_TOKEN=$busToken"
        "STEAM_WEB_API_KEY=$steamKey"
    ) | Set-Content -Path $envPath -Encoding ASCII
    Write-Host ("Wrote {0}" -f $envPath) -ForegroundColor DarkGray
    Write-Host ("Operator key (save for production-cutover-ops): {0}" -f $operatorKey) -ForegroundColor Yellow
    $script:GeneratedOperatorKey = $operatorKey
}

Write-Host "=== NL Phase 10 production cutover stack ===" -ForegroundColor Cyan
Write-Host "Production flags: mock off, live/launch dev off, GA require production ready" -ForegroundColor DarkGray

foreach ($port in @(27020, 443, 8443)) {
    if (Test-PortInUse $port) {
        Write-Host ("Port {0} busy - stop other NL stacks first." -f $port) -ForegroundColor Yellow
        throw ("Port {0} busy." -f $port)
    }
}

$hostData = Join-Path $Root "docker\production-cutover-data"
New-Item -ItemType Directory -Force -Path $hostData | Out-Null
Write-CutoverEnvFile $hostData

if (-not $SkipForkImages) {
    Write-Host "Building production fork images..." -ForegroundColor Yellow
    & (Join-Path $Root "scripts/build-fork-images.ps1") -Images @("hello-fork", "minecraft", "beamng")
    if ($LASTEXITCODE -ne 0) { throw "build-fork-images failed" }
}

$composeArgs = @("compose", "-f", "docker/docker-compose.production-cutover.yml", "up")
if (-not $SkipBuild) { $composeArgs += "--build" }
$composeArgs += @("-d")
& docker @composeArgs
if ($LASTEXITCODE -ne 0) { throw "docker compose up failed" }

function Wait-HttpOk([string]$Url, [int]$TimeoutSec = 240) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri $Url -TimeoutSec 5 | Out-Null
            return $true
        } catch {
            Start-Sleep -Seconds 3
        }
    }
    return $false
}

if (-not (Wait-HttpOk "http://127.0.0.1:27020/health")) {
    & docker compose -f docker/docker-compose.production-cutover.yml logs session-host --tail 40
    throw "session-host /health failed"
}

Write-Host "Cutover ops:  http://127.0.0.1:27020/production-cutover-ops.html" -ForegroundColor Green
Write-Host "HTTPS edge:   https://127.0.0.1/health" -ForegroundColor Green
Write-Host "Status page:  http://127.0.0.1:27020/status.html" -ForegroundColor Green

if ($Validate) {
    Write-Host ""
    & (Join-Path $Root "scripts/nl-production-cutover-validate.ps1") -OperatorKey $script:GeneratedOperatorKey
}
