# Phase 4 — start production fleet stack (Docker fork provisioner + edge/relay/TURN)
param(
    [switch]$SkipBuild,
    [switch]$SkipForkImage,
    [switch]$Validate,
    [int]$ConcurrentSessions = 100
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-PortInUse([int]$Port) {
    try {
        return (Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue).TcpTestSucceeded
    } catch {
        return $false
    }
}

function Write-ProductionEnvFile {
    param([string]$HostDataRoot)
    $envPath = Join-Path $Root "docker\production-fleet.env"
    $hostPath = $HostDataRoot.Replace('\', '/')
    @(
        "# Auto-generated by nl-production-stack-up.ps1 - host bind mount for Docker fork volumes"
        "NL_FORK_DOCKER_WORKSPACE_HOST_ROOT=$hostPath"
    ) | Set-Content -Path $envPath -Encoding ASCII
    Write-Host ("Wrote {0}" -f $envPath) -ForegroundColor DarkGray
}

Write-Host "=== NL Phase 4 production fleet stack ===" -ForegroundColor Cyan

foreach ($port in @(27020, 443, 8443)) {
    if (Test-PortInUse $port) {
        Write-Host ("Port {0} is already in use." -f $port) -ForegroundColor Yellow
        Write-Host "Stop staging/production stack or local dotnet run first:" -ForegroundColor Yellow
        Write-Host "  powershell -File scripts/nl-production-stack-down.ps1" -ForegroundColor DarkGray
        Write-Host "  powershell -File scripts/nl-staging-stack-down.ps1" -ForegroundColor DarkGray
        throw ("Port {0} busy - cannot start production stack." -f $port)
    }
}

$hostData = Join-Path $Root "docker\production-data"
New-Item -ItemType Directory -Force -Path $hostData | Out-Null
Write-ProductionEnvFile $hostData

if (-not $SkipForkImage) {
    Write-Host "Building nl-fork-hello:latest ..." -ForegroundColor Yellow
    docker build -f docker/fork-hello/Dockerfile -t nl-fork-hello:latest .
    if ($LASTEXITCODE -ne 0) {
        throw "docker build nl-fork-hello failed"
    }
}

$composeArgs = @("compose", "-f", "docker/docker-compose.production-fleet.yml", "up")
if (-not $SkipBuild) { $composeArgs += "--build" }
$composeArgs += @("-d")

Write-Host "Starting docker compose production fleet..." -ForegroundColor Yellow
& docker @composeArgs
if ($LASTEXITCODE -ne 0) {
    throw "docker compose up failed"
}

function Wait-HttpOk([string]$Url, [int]$TimeoutSec = 240) {
    Write-Host ("Waiting for {0} ..." -f $Url) -ForegroundColor DarkGray
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri $Url -TimeoutSec 5 | Out-Null
            return $true
        } catch {
            Start-Sleep -Seconds 3
        }
    }
    return $false
}

if (-not (Wait-HttpOk "http://127.0.0.1:27020/health")) {
    Write-Host "session-host logs:" -ForegroundColor Red
    & docker compose -f docker/docker-compose.production-fleet.yml logs session-host --tail 50
    throw "session-host /health did not become ready"
}

$orch = Invoke-RestMethod -Uri "http://127.0.0.1:27020/api/v1/fork/orchestrator/settings" -TimeoutSec 10
Write-Host ("Orchestrator mode: {0}" -f $orch.mode) -ForegroundColor Green
Write-Host "Session host:  http://127.0.0.1:27020" -ForegroundColor Green
Write-Host "HTTPS edge:    https://127.0.0.1/health" -ForegroundColor Green
Write-Host "Relay stub:    wss://127.0.0.1:8443/fork/{sessionId}" -ForegroundColor Green
Write-Host "TURN:          turn:127.0.0.1:3478" -ForegroundColor Green
Write-Host "Operator UI:   http://127.0.0.1:27020/fleet-ops.html" -ForegroundColor Green

if ($Validate) {
    Write-Host ""
    & (Join-Path $Root "scripts/nl-production-validate.ps1") -ConcurrentSessions $ConcurrentSessions
}
