# Production dogfood — start stack (GA launch + Docker fork provisioner)
param(
    [switch]$SkipBuild,
    [switch]$SkipClientPackage,
    [switch]$SkipForkImages,
    [switch]$Validate
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-PortInUse([int]$Port) {
    try {
        return (Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue).TcpTestSucceeded
    } catch {
        return $false
    }
}

function New-RandomHex([int]$Bytes = 32) {
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLowerInvariant()
}

function Write-DogfoodEnvFile {
    param([string]$HostDataRoot)
    $envPath = Join-Path $Root "docker\production-dogfood-fleet.env"
    $hostPath = $HostDataRoot.Replace('\', '/')
    $operatorKey = New-RandomHex 16
    $busToken = New-RandomHex 16
    $steamKey = New-RandomHex 16
    @(
        "# Auto-generated by nl-production-dogfood-stack-up.ps1"
        "NL_FORK_DOCKER_WORKSPACE_HOST_ROOT=$hostPath"
        "NL_OPERATOR_KEY=$operatorKey"
        "NL_BUS_TOKEN=$busToken"
        "STEAM_WEB_API_KEY=$steamKey"
    ) | Set-Content -Path $envPath -Encoding ASCII
    Write-Host ("Operator key (save for production-dogfood-ops): {0}" -f $operatorKey) -ForegroundColor Yellow
    $script:GeneratedOperatorKey = $operatorKey
}

Write-Host "=== NL production dogfood stack ===" -ForegroundColor Cyan

foreach ($port in @(27020, 443, 8443)) {
    if (Test-PortInUse $port) {
        throw ("Port {0} busy - stop other NL stacks first." -f $port)
    }
}

if (-not $SkipForkImages) {
    Write-Host "Building production fork images (hello-fork, minecraft, beamng)..." -ForegroundColor Yellow
    & (Join-Path $Root "scripts/build-fork-images.ps1") -Images @("hello-fork", "minecraft", "beamng")
    if ($LASTEXITCODE -ne 0) { throw "build-fork-images failed" }
}

if (-not $SkipClientPackage) {
    & (Join-Path $Root "scripts/build-nl-client-package.ps1") -Version "1.0.0"
    if ($LASTEXITCODE -ne 0) { throw "build-nl-client-package failed" }
}

$hostData = Join-Path $Root "docker\production-dogfood-data"
New-Item -ItemType Directory -Force -Path $hostData | Out-Null
Write-DogfoodEnvFile $hostData

$composeArgs = @("compose", "-f", "docker/docker-compose.production-dogfood.yml", "up")
if (-not $SkipBuild) { $composeArgs += "--build" }
$composeArgs += @("-d")
& docker @composeArgs
if ($LASTEXITCODE -ne 0) { throw "docker compose up failed" }

function Wait-HttpOk([string]$Url, [int]$TimeoutSec = 240) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri $Url -TimeoutSec 5 | Out-Null
            return $true
        } catch {
            Start-Sleep -Seconds 3
        }
    }
    return $false
}

if (-not (Wait-HttpOk "http://127.0.0.1:27020/health")) {
    throw "session-host /health failed"
}

Write-Host "Dogfood ops:   http://127.0.0.1:27020/production-dogfood-ops.html" -ForegroundColor Green
Write-Host "Identity link: http://127.0.0.1:27020/identity-link.html" -ForegroundColor Green
Write-Host "NL Client:     http://127.0.0.1:27020/nl-client.html" -ForegroundColor Green

if ($Validate) {
    Write-Host ""
    & (Join-Path $Root "scripts/nl-production-dogfood-validate.ps1") -OperatorKey $script:GeneratedOperatorKey -AllGames
}
