# Phase 12 — start scale & reliability stack
param(
    [switch]$SkipBuild,
    [switch]$SkipClientPackage,
    [switch]$Validate
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
Set-Location $Root

function Test-PortInUse([int]$Port) {
    try {
        return (Test-NetConnection -ComputerName 127.0.0.1 -Port $Port -WarningAction SilentlyContinue).TcpTestSucceeded
    } catch {
        return $false
    }
}

function New-RandomHex([int]$Bytes = 32) {
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLowerInvariant()
}

function Write-ScaleEnvFile {
    param([string]$HostDataRoot)
    $envPath = Join-Path $Root "docker\scale-reliability-fleet.env"
    $hostPath = $HostDataRoot.Replace('\', '/')
    $operatorKey = New-RandomHex 16
    $busToken = New-RandomHex 16
    $steamKey = New-RandomHex 16
    @(
        "# Auto-generated by nl-scale-reliability-stack-up.ps1"
        "NL_FORK_DOCKER_WORKSPACE_HOST_ROOT=$hostPath"
        "NL_OPERATOR_KEY=$operatorKey"
        "NL_BUS_TOKEN=$busToken"
        "STEAM_WEB_API_KEY=$steamKey"
    ) | Set-Content -Path $envPath -Encoding ASCII
    Write-Host ("Operator key (save for scale-reliability-ops): {0}" -f $operatorKey) -ForegroundColor Yellow
    $script:GeneratedOperatorKey = $operatorKey
}

Write-Host "=== NL Phase 12 scale & reliability stack ===" -ForegroundColor Cyan

foreach ($port in @(27020, 443, 8443)) {
    if (Test-PortInUse $port) {
        throw ("Port {0} busy - stop other NL stacks first." -f $port)
    }
}

if (-not $SkipClientPackage) {
    & (Join-Path $Root "scripts/build-nl-client-package.ps1") -Version "1.0.0"
    if ($LASTEXITCODE -ne 0) { throw "build-nl-client-package failed" }
}

$hostData = Join-Path $Root "docker\scale-reliability-data"
New-Item -ItemType Directory -Force -Path $hostData | Out-Null
Write-ScaleEnvFile $hostData

$composeArgs = @("compose", "-f", "docker/docker-compose.scale-reliability.yml", "up")
if (-not $SkipBuild) { $composeArgs += "--build" }
$composeArgs += @("-d")
& docker @composeArgs
if ($LASTEXITCODE -ne 0) { throw "docker compose up failed" }

function Wait-HttpOk([string]$Url, [int]$TimeoutSec = 240) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    while ((Get-Date) -lt $deadline) {
        try {
            Invoke-RestMethod -Uri $Url -TimeoutSec 5 | Out-Null
            return $true
        } catch {
            Start-Sleep -Seconds 3
        }
    }
    return $false
}

if (-not (Wait-HttpOk "http://127.0.0.1:27020/health")) {
    throw "session-host /health failed"
}

Write-Host "Scale ops:     http://127.0.0.1:27020/scale-reliability-ops.html" -ForegroundColor Green
Write-Host "Fleet ops:     http://127.0.0.1:27020/fleet-ops.html" -ForegroundColor Green

if ($Validate) {
    Write-Host ""
    & (Join-Path $Root "scripts/nl-scale-reliability-validate.ps1") -OperatorKey $script:GeneratedOperatorKey
}
